### ISSUE TITLE
warning: circular argument reference - name

### ISSUE THREAD

**Issue by KomalDhanwani** [robhurring/address-validator#2]
@robhurring 

There are some warnings coming in address initialize method in ruby 2.2.3

I have added some fix for it if you want to check https://github.com/KomalDhanwani/address-validator/commit/4aa287b7cb1b382399c9de545f66fb8b5db95c01 

if its ok merge it in your branch...

**Comment by robhurring** [comment]
Merged. Ty :+1:

**Comment by KomalDhanwani** [comment]
@robhurring   thanks :)
