### ISSUE TITLE
List of candidates gives street1 value as a range

### ISSUE THREAD

**Issue by andrey-ka** [robhurring/address-validator#9]
Hi there,
We are using your gem for UPS address verification with custom extension to include candidate list. We found that when we receive response with ambiguous address indicator,
candidate list contains street number suggestions in a range format, like '1-21 Some street', '2-20 Some street'
Could you please give a hint (or request option) how to receive a candidate list where street suggestion not in range format?
Please let me know, if you need more details.
Thanks in advance!

**Comment by robhurring** [comment]
I haven't been using this library that much in my current job, but I can check through the UPS API  documentation and see if theres any flags I can pass to do this. Do you have a sample address I could use to test with?

**Comment by andrey-ka** [comment]
Hi. @robhurring 
I have an address data with ambiguous response indicator and candidate list.
Many thanks for your efforts.
[request_response_NY.zip](https://github.com/robhurring/address-validator/files/250068/request_response_NY.zip)

**Comment by andrey-ka** [comment]
We've implemented address validation to work with street address ranges.
